# Generated by Django 4.2.30 on 2026-06-27 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SsotDocumentIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=500, unique=True)),
                ("exists", models.BooleanField(default=False)),
                (
                    "declared_hash",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("actual_hash", models.CharField(blank=True, max_length=64, null=True)),
                ("hash_status", models.CharField(max_length=40)),
                (
                    "referenced_by_event_id",
                    models.CharField(blank=True, max_length=160, null=True),
                ),
                (
                    "stream_path",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("event_line", models.PositiveIntegerField(blank=True, null=True)),
                ("indexed_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["path"],
                "indexes": [
                    models.Index(
                        fields=["hash_status"], name="ssot_index__hash_st_3e53e7_idx"
                    ),
                    models.Index(
                        fields=["referenced_by_event_id"],
                        name="ssot_index__referen_4d7177_idx",
                    ),
                    models.Index(
                        fields=["stream_path", "event_line"],
                        name="ssot_index__stream__6451d1_idx",
                    ),
                    models.Index(
                        fields=["indexed_at"], name="ssot_index__indexed_5be75b_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EventStreamIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stream_path", models.CharField(max_length=500, unique=True)),
                ("tenant", models.CharField(blank=True, max_length=160, null=True)),
                ("event_count", models.PositiveIntegerField(default=0)),
                (
                    "last_event_id",
                    models.CharField(blank=True, max_length=160, null=True),
                ),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("indexed_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["stream_path"],
                "indexes": [
                    models.Index(
                        fields=["tenant"], name="ssot_index__tenant_7912ef_idx"
                    ),
                    models.Index(
                        fields=["last_seen_at"], name="ssot_index__last_se_466ee4_idx"
                    ),
                    models.Index(
                        fields=["indexed_at"], name="ssot_index__indexed_3336e2_idx"
                    ),
                ],
            },
        ),
    ]
