# Generated by Codex for Relinium source registry v0.1.

from __future__ import annotations

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DataSource",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("label", models.CharField(max_length=220)),
                ("source_type", models.CharField(choices=[("local_folder", "Local folder"), ("network_share", "Network share"), ("server", "Server"), ("cloud_ged", "Cloud / GED"), ("other", "Other")], max_length=32)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("ready", "Ready"), ("observed", "Observed"), ("error", "Error"), ("disabled", "Disabled")], default="draft", max_length=32)),
                ("locator_ref", models.CharField(blank=True, max_length=700)),
                ("locator_hash", models.CharField(blank=True, max_length=64)),
                ("read_only", models.BooleanField(default=True)),
                ("include_hidden", models.BooleanField(default=True)),
                ("follow_symlinks", models.BooleanField(default=False)),
                ("exclusions", models.JSONField(blank=True, default=list)),
                ("notes_redacted", models.TextField(blank=True)),
                ("last_observed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="DataSourceAuditEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("event_type", models.CharField(choices=[("created", "Created"), ("updated", "Updated"), ("disabled", "Disabled"), ("marked_ready", "Marked ready"), ("observation_requested", "Observation requested"), ("observation_completed", "Observation completed"), ("observation_failed", "Observation failed")], max_length=40)),
                ("actor_label", models.CharField(blank=True, max_length=160, null=True)),
                ("details_redacted", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("source", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="audit_events", to="source_registry.datasource")),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddIndex(model_name="datasource", index=models.Index(fields=["source_type"], name="source_regi_source__fe476c_idx")),
        migrations.AddIndex(model_name="datasource", index=models.Index(fields=["status"], name="source_regi_status_4bf875_idx")),
        migrations.AddIndex(model_name="datasource", index=models.Index(fields=["locator_hash"], name="source_regi_locator_cf5328_idx")),
        migrations.AddIndex(model_name="datasource", index=models.Index(fields=["source_type", "status"], name="source_regi_source__3e2444_idx")),
        migrations.AddIndex(model_name="datasourceauditevent", index=models.Index(fields=["source", "created_at"], name="source_regi_source__8abd16_idx")),
        migrations.AddIndex(model_name="datasourceauditevent", index=models.Index(fields=["event_type"], name="source_regi_event_t_db29ab_idx")),
        migrations.AddIndex(model_name="datasourceauditevent", index=models.Index(fields=["created_at"], name="source_regi_created_b547a4_idx")),
    ]
