# Generated by Django 4.2.30 on 2026-06-28 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("source_registry", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasource",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="data_sources",
                to="accounts.organization",
            ),
        ),
        migrations.AddIndex(
            model_name="datasource",
            index=models.Index(
                fields=["organization", "status"], name="source_regi_organiz_4cd32c_idx"
            ),
        ),
    ]
