# Generated by Django 4.2.30 on 2026-06-27 12:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("actor", models.CharField(blank=True, max_length=160, null=True)),
                ("action", models.CharField(max_length=160)),
                ("target_type", models.CharField(max_length=120)),
                ("target_ref", models.CharField(max_length=500)),
                ("metadata_redacted", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["actor"], name="auditlog_au_actor_782205_idx"),
                    models.Index(
                        fields=["action"], name="auditlog_au_action_4744c0_idx"
                    ),
                    models.Index(
                        fields=["target_type", "target_ref"],
                        name="auditlog_au_target__81bc5a_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="auditlog_au_created_320ace_idx"
                    ),
                ],
            },
        ),
    ]
