# Generated by Django 4.2.30 on 2026-06-27 12:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ValidationRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("strict", "Strict"), ("baseline", "Baseline")],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("passed", "Passed"),
                            ("failed", "Failed"),
                            ("error", "Error"),
                        ],
                        max_length=16,
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("finding_count", models.PositiveIntegerField(default=0)),
                ("matched_baseline_count", models.PositiveIntegerField(default=0)),
                (
                    "validator_version",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                (
                    "ssot_snapshot_hash",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-started_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["mode", "status"], name="ssot_valida_mode_b62a89_idx"
                    ),
                    models.Index(
                        fields=["started_at"], name="ssot_valida_started_3022f0_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="ssot_valida_created_e87357_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ValidationFindingRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=120)),
                ("severity", models.CharField(max_length=32)),
                ("event_id", models.CharField(blank=True, max_length=160, null=True)),
                ("stream_path", models.CharField(max_length=500)),
                ("line_number", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "raw_line_sha256",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("message_redacted", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="findings",
                        to="ssot_validation.validationrun",
                    ),
                ),
            ],
            options={
                "ordering": ["stream_path", "line_number", "code"],
                "indexes": [
                    models.Index(
                        fields=["run", "code"], name="ssot_valida_run_id_6c95f5_idx"
                    ),
                    models.Index(
                        fields=["event_id"], name="ssot_valida_event_i_a989fa_idx"
                    ),
                    models.Index(
                        fields=["stream_path", "line_number"],
                        name="ssot_valida_stream__d1d29b_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="ssot_valida_created_18b1b0_idx"
                    ),
                ],
            },
        ),
    ]
