# Generated by Django 4.2.30 on 2026-06-28 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email_hash", models.CharField(max_length=64)),
                ("email_redacted", models.CharField(max_length=180)),
                ("organization_hint", models.CharField(blank=True, max_length=180)),
                (
                    "requested_role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("admin", "Admin"),
                            ("analyst", "Analyst"),
                            ("operator", "Operator"),
                            ("viewer", "Viewer"),
                        ],
                        default="viewer",
                        max_length=24,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=24,
                    ),
                ),
                ("message_redacted", models.TextField(blank=True)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-requested_at"],
            },
        ),
        migrations.CreateModel(
            name="AuthAuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("action", models.CharField(max_length=120)),
                ("target_type", models.CharField(max_length=120)),
                ("target_ref", models.CharField(max_length=255)),
                ("ip_hash", models.CharField(blank=True, max_length=64, null=True)),
                ("user_agent_redacted", models.CharField(blank=True, max_length=255)),
                ("metadata_redacted", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OAuthIdentity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("provider", models.CharField(max_length=80)),
                ("issuer", models.CharField(max_length=255)),
                ("subject", models.CharField(max_length=255)),
                ("email_claim_hash", models.CharField(blank=True, max_length=64)),
                ("last_login_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["provider", "issuer"],
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("slug", models.SlugField(max_length=80, unique=True)),
                ("name", models.CharField(max_length=180)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("suspended", "Suspended")],
                        default="active",
                        max_length=24,
                    ),
                ),
                (
                    "mfa_policy",
                    models.CharField(
                        choices=[
                            ("off", "Off"),
                            ("optional", "Optional"),
                            ("required", "Required"),
                        ],
                        default="off",
                        max_length=24,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("display_name", models.CharField(max_length=180)),
                ("avatar_initials", models.CharField(blank=True, max_length=8)),
                ("locale", models.CharField(default="fr-FR", max_length=16)),
                ("timezone", models.CharField(default="Europe/Paris", max_length=64)),
                ("mfa_required", models.BooleanField(default=False)),
                ("mfa_enrolled", models.BooleanField(default=False)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "selected_organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="selected_by_profiles",
                        to="accounts.organization",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relinium_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["display_name"],
            },
        ),
        migrations.CreateModel(
            name="OrganizationMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("admin", "Admin"),
                            ("analyst", "Analyst"),
                            ("operator", "Operator"),
                            ("viewer", "Viewer"),
                        ],
                        default="viewer",
                        max_length=24,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("invited", "Invited"),
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("revoked", "Revoked"),
                        ],
                        default="invited",
                        max_length=24,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_membership_invites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="accounts.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["organization__name", "user__email"],
            },
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(fields=["slug"], name="accounts_or_slug_7a4a7c_idx"),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(fields=["status"], name="accounts_or_status_075bc9_idx"),
        ),
        migrations.AddField(
            model_name="oauthidentity",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="oauth_identities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="authauditevent",
            name="actor_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="auth_audit_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="authauditevent",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="auth_audit_events",
                to="accounts.organization",
            ),
        ),
        migrations.AddField(
            model_name="accessrequest",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_access_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(
                fields=["selected_organization"], name="accounts_us_selecte_946c8e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(
                fields=["mfa_required", "mfa_enrolled"],
                name="accounts_us_mfa_req_4602d3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="organizationmembership",
            index=models.Index(
                fields=["organization", "role"], name="accounts_or_organiz_eae39b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organizationmembership",
            index=models.Index(
                fields=["organization", "status"], name="accounts_or_organiz_a84792_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organizationmembership",
            index=models.Index(
                fields=["user", "status"], name="accounts_or_user_id_d59994_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="organizationmembership",
            constraint=models.UniqueConstraint(
                fields=("organization", "user"), name="uniq_membership_per_org_user"
            ),
        ),
        migrations.AddIndex(
            model_name="oauthidentity",
            index=models.Index(
                fields=["user", "provider"], name="accounts_oa_user_id_170745_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="oauthidentity",
            index=models.Index(
                fields=["email_claim_hash"], name="accounts_oa_email_c_61a7d6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="oauthidentity",
            index=models.Index(
                fields=["last_login_at"], name="accounts_oa_last_lo_7c18dd_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="oauthidentity",
            constraint=models.UniqueConstraint(
                fields=("provider", "issuer", "subject"),
                name="uniq_oauth_identity_provider_issuer_subject",
            ),
        ),
        migrations.AddIndex(
            model_name="authauditevent",
            index=models.Index(
                fields=["actor_user", "created_at"],
                name="accounts_au_actor_u_a5a0da_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="authauditevent",
            index=models.Index(
                fields=["organization", "created_at"],
                name="accounts_au_organiz_f49564_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="authauditevent",
            index=models.Index(fields=["action"], name="accounts_au_action_0bd0ad_idx"),
        ),
        migrations.AddIndex(
            model_name="authauditevent",
            index=models.Index(
                fields=["target_type", "target_ref"],
                name="accounts_au_target__0d3f3d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="authauditevent",
            index=models.Index(
                fields=["created_at"], name="accounts_au_created_78fa16_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accessrequest",
            index=models.Index(
                fields=["email_hash"], name="accounts_ac_email_h_a1cf84_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accessrequest",
            index=models.Index(
                fields=["status", "requested_at"], name="accounts_ac_status_5e4df1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accessrequest",
            index=models.Index(
                fields=["requested_role"], name="accounts_ac_request_dbcc59_idx"
            ),
        ),
    ]
