# Generated by Django 4.2.28 on 2026-06-27 14:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CaseCorrelation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "correlation_type",
                    models.CharField(
                        choices=[
                            ("shared_domain", "Shared domain"),
                            ("shared_url_pattern", "Shared URL pattern"),
                            ("shared_phone", "Shared phone"),
                            ("shared_iban", "Shared IBAN"),
                            ("shared_ip", "Shared IP"),
                            ("shared_text_pattern", "Shared text pattern"),
                            ("shared_hash", "Shared hash"),
                            ("shared_campaign", "Shared campaign"),
                        ],
                        max_length=32,
                    ),
                ),
                ("score", models.FloatField(default=0.0)),
                ("explanation", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-score", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CustodyEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created_case", "Created case"),
                            ("ingested_artifact", "Ingested artifact"),
                            ("hashed_artifact", "Hashed artifact"),
                            ("extracted_indicator", "Extracted indicator"),
                            ("added_statement", "Added statement"),
                            ("generated_report", "Generated report"),
                            ("reviewed_report", "Reviewed report"),
                            ("exported_report", "Exported report"),
                        ],
                        max_length=32,
                    ),
                ),
                ("actor_label", models.CharField(default="operator", max_length=160)),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                ("details_redacted", models.JSONField(blank=True, default=dict)),
                ("event_hash", models.CharField(db_index=True, max_length=64)),
            ],
            options={
                "ordering": ["occurred_at"],
            },
        ),
        migrations.CreateModel(
            name="EvidenceArtifact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "artifact_type",
                    models.CharField(
                        choices=[
                            ("eml", "EML"),
                            ("sms_text", "SMS text"),
                            ("screenshot", "Screenshot"),
                            ("call_note", "Call note"),
                            ("document", "Document"),
                            ("url", "URL"),
                            ("bank_record", "Bank record"),
                            ("log_export", "Log export"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "original_filename_redacted",
                    models.CharField(blank=True, max_length=260, null=True),
                ),
                ("sha256", models.CharField(db_index=True, max_length=64)),
                ("size_bytes", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "storage_ref",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("ingested_at", models.DateTimeField(auto_now_add=True)),
                ("source_description", models.TextField(blank=True)),
                (
                    "integrity_status",
                    models.CharField(
                        choices=[
                            ("declared", "Declared"),
                            ("hashed", "Hashed"),
                            ("hash_mismatch", "Hash mismatch"),
                            ("unchecked", "Unchecked"),
                        ],
                        default="hashed",
                        max_length=32,
                    ),
                ),
                ("metadata_redacted", models.JSONField(blank=True, default=dict)),
                ("raw_content_storage_allowed", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-ingested_at"],
            },
        ),
        migrations.CreateModel(
            name="GeneratedReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("victim", "Victim"),
                            ("authorities", "Authorities"),
                            ("bank", "Bank"),
                            ("company", "Company"),
                            ("technical", "Technical"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[("markdown", "Markdown")],
                        default="markdown",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("reviewed", "Reviewed"),
                            ("exported", "Exported"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("content_markdown", models.TextField()),
                ("sha256", models.CharField(db_index=True, max_length=64)),
                ("generated_at", models.DateTimeField(auto_now=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["report_type"],
            },
        ),
        migrations.CreateModel(
            name="ScamCase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=220)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("ready_for_review", "Ready for review"),
                            ("reported", "Reported"),
                            ("closed", "Closed"),
                        ],
                        default="draft",
                        max_length=32,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=16,
                    ),
                ),
                (
                    "initial_vector",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("call", "Call"),
                            ("chat", "Messaging"),
                            ("document", "Document"),
                            ("usb", "USB"),
                            ("website", "Website"),
                            ("bank_transaction", "Bank transaction"),
                            ("remote_access", "Remote access"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=32,
                    ),
                ),
                (
                    "victim_type",
                    models.CharField(
                        choices=[
                            ("individual", "Individual"),
                            ("company", "Company"),
                            ("association", "Association"),
                            ("public_entity", "Public entity"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=32,
                    ),
                ),
                ("victim_label_redacted", models.CharField(blank=True, max_length=220)),
                ("discovered_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("summary", models.TextField(blank=True)),
                ("operator_notes_redacted", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TimelineEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("occurred_at", models.DateTimeField(blank=True, null=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("opened", "Opened"),
                            ("clicked", "Clicked"),
                            ("submitted_credentials", "Submitted credentials"),
                            ("submitted_payment", "Submitted payment"),
                            ("phone_call", "Phone call"),
                            ("remote_access", "Remote access"),
                            ("transfer", "Transfer"),
                            ("discovery", "Discovery"),
                            ("remediation", "Remediation"),
                            ("report", "Report"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                ("label", models.CharField(max_length=220)),
                ("description_redacted", models.TextField(blank=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("victim_statement", "Victim statement"),
                            ("artifact", "Artifact"),
                            ("technical_analysis", "Technical analysis"),
                            ("bank_record", "Bank record"),
                            ("operator", "Operator"),
                            ("correlation", "Correlation"),
                        ],
                        max_length=32,
                    ),
                ),
                ("confidence", models.FloatField(default=0.7)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeline_events",
                        to="scam_trace.scamcase",
                    ),
                ),
                (
                    "related_artifact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="timeline_events",
                        to="scam_trace.evidenceartifact",
                    ),
                ),
            ],
            options={
                "ordering": ["occurred_at", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="TechnicalIndicator",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "indicator_type",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("domain", "Domain"),
                            ("url", "URL"),
                            ("ip", "IP"),
                            ("phone", "Phone"),
                            ("iban", "IBAN"),
                            ("crypto_wallet", "Crypto wallet"),
                            ("hash", "Hash"),
                            ("attachment_name", "Attachment name"),
                            ("user_account", "User account"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                ("value_redacted", models.CharField(max_length=500)),
                ("value_hash", models.CharField(max_length=64)),
                ("first_seen_at", models.DateTimeField(auto_now_add=True)),
                ("risk_level", models.CharField(default="medium", max_length=16)),
                ("confidence", models.FloatField(default=0.7)),
                ("notes_redacted", models.TextField(blank=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indicators",
                        to="scam_trace.scamcase",
                    ),
                ),
                (
                    "source_artifact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="indicators",
                        to="scam_trace.evidenceartifact",
                    ),
                ),
            ],
            options={
                "ordering": ["indicator_type", "value_redacted"],
            },
        ),
        migrations.CreateModel(
            name="ScamQuestionnaireAnswer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("question_key", models.CharField(max_length=120)),
                ("answer_type", models.CharField(max_length=32)),
                ("answer_value_redacted", models.JSONField(blank=True, default=dict)),
                ("answered_at", models.DateTimeField(auto_now=True)),
                ("confidence", models.FloatField(default=0.7)),
                ("notes_redacted", models.TextField(blank=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questionnaire_answers",
                        to="scam_trace.scamcase",
                    ),
                ),
            ],
            options={
                "ordering": ["question_key"],
            },
        ),
        migrations.AddIndex(
            model_name="scamcase",
            index=models.Index(
                fields=["status", "severity"], name="scam_trace__status_3d9e45_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scamcase",
            index=models.Index(
                fields=["initial_vector"], name="scam_trace__initial_c1e419_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scamcase",
            index=models.Index(
                fields=["created_at"], name="scam_trace__created_ed6099_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scamcase",
            index=models.Index(
                fields=["updated_at"], name="scam_trace__updated_5eaa14_idx"
            ),
        ),
        migrations.AddField(
            model_name="generatedreport",
            name="case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="scam_trace.scamcase",
            ),
        ),
        migrations.AddField(
            model_name="evidenceartifact",
            name="case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="artifacts",
                to="scam_trace.scamcase",
            ),
        ),
        migrations.AddField(
            model_name="custodyevent",
            name="artifact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="custody_events",
                to="scam_trace.evidenceartifact",
            ),
        ),
        migrations.AddField(
            model_name="custodyevent",
            name="case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="custody_events",
                to="scam_trace.scamcase",
            ),
        ),
        migrations.AddField(
            model_name="casecorrelation",
            name="source_case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="outgoing_correlations",
                to="scam_trace.scamcase",
            ),
        ),
        migrations.AddField(
            model_name="casecorrelation",
            name="target_case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incoming_correlations",
                to="scam_trace.scamcase",
            ),
        ),
        migrations.AddIndex(
            model_name="timelineevent",
            index=models.Index(
                fields=["case", "occurred_at"], name="scam_trace__case_id_1da238_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="timelineevent",
            index=models.Index(
                fields=["case", "created_at"], name="scam_trace__case_id_2a41eb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="timelineevent",
            index=models.Index(
                fields=["event_type"], name="scam_trace__event_t_b521cf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="timelineevent",
            index=models.Index(
                fields=["created_at"], name="scam_trace__created_d3f347_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="technicalindicator",
            index=models.Index(
                fields=["case", "indicator_type"], name="scam_trace__case_id_311ea5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="technicalindicator",
            index=models.Index(
                fields=["indicator_type"], name="scam_trace__indicat_f647c0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="technicalindicator",
            index=models.Index(
                fields=["value_hash"], name="scam_trace__value_h_c97895_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="technicalindicator",
            index=models.Index(
                fields=["first_seen_at"], name="scam_trace__first_s_93c99b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="technicalindicator",
            constraint=models.UniqueConstraint(
                fields=("case", "indicator_type", "value_hash"),
                name="uniq_scam_indicator_per_case",
            ),
        ),
        migrations.AddIndex(
            model_name="scamquestionnaireanswer",
            index=models.Index(
                fields=["case", "question_key"], name="scam_trace__case_id_7a1868_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scamquestionnaireanswer",
            index=models.Index(
                fields=["answered_at"], name="scam_trace__answere_669357_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="scamquestionnaireanswer",
            constraint=models.UniqueConstraint(
                fields=("case", "question_key"),
                name="uniq_scam_answer_per_case_question",
            ),
        ),
        migrations.AddIndex(
            model_name="generatedreport",
            index=models.Index(
                fields=["case", "report_type"], name="scam_trace__case_id_a3f1e8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="generatedreport",
            index=models.Index(fields=["sha256"], name="scam_trace__sha256_e98662_idx"),
        ),
        migrations.AddIndex(
            model_name="generatedreport",
            index=models.Index(
                fields=["generated_at"], name="scam_trace__generat_2f926c_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="generatedreport",
            constraint=models.UniqueConstraint(
                fields=("case", "report_type"), name="uniq_scam_report_per_case_type"
            ),
        ),
        migrations.AddIndex(
            model_name="evidenceartifact",
            index=models.Index(
                fields=["case", "ingested_at"], name="scam_trace__case_id_3a8685_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="evidenceartifact",
            index=models.Index(fields=["sha256"], name="scam_trace__sha256_0a0e64_idx"),
        ),
        migrations.AddIndex(
            model_name="evidenceartifact",
            index=models.Index(
                fields=["artifact_type"], name="scam_trace__artifac_839c84_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="custodyevent",
            index=models.Index(
                fields=["case", "occurred_at"], name="scam_trace__case_id_a51201_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="custodyevent",
            index=models.Index(
                fields=["artifact", "occurred_at"],
                name="scam_trace__artifac_f34222_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="custodyevent",
            index=models.Index(
                fields=["event_hash"], name="scam_trace__event_h_12ee0d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="casecorrelation",
            index=models.Index(
                fields=["source_case", "created_at"],
                name="scam_trace__source__7487da_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="casecorrelation",
            index=models.Index(
                fields=["target_case", "created_at"],
                name="scam_trace__target__57e6ec_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="casecorrelation",
            index=models.Index(
                fields=["correlation_type"], name="scam_trace__correla_76ec54_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="casecorrelation",
            index=models.Index(
                fields=["created_at"], name="scam_trace__created_912eb7_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="casecorrelation",
            constraint=models.UniqueConstraint(
                fields=("source_case", "target_case", "correlation_type"),
                name="uniq_scam_case_correlation",
            ),
        ),
    ]
