# Generated by Django 4.2.30 on 2026-06-28 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("scam_trace", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scamcase",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scam_cases",
                to="accounts.organization",
            ),
        ),
        migrations.AddIndex(
            model_name="scamcase",
            index=models.Index(
                fields=["organization", "status"], name="scam_trace__organiz_fbecc8_idx"
            ),
        ),
    ]
